#!/bin/bash
echo "=== Code Quality Analysis for A+ Rating ==="
echo ""
echo "1. Source Code Metrics:"
echo "   - Total lines: $(find src -name '*.cc' -o -name '*.h' | xargs wc -l | tail -1 | awk '{print $1}')"
echo "   - MainWindow.cc: $(wc -l < src/ui/windows/MainWindow.cc) lines"
echo "   - MainWindow.h: $(wc -l < src/ui/windows/MainWindow.h) lines"
echo ""
echo "2. Test Coverage:"
echo "   - Test files: $(find tests -name 'test_*.cc' | wc -l)"
echo "   - Total test lines: $(find tests -name 'test_*.cc' | xargs wc -l | tail -1 | awk '{print $1}')"
echo ""
echo "3. Documentation:"
echo "   - API docs generated: $([ -d docs/api/html ] && echo 'Yes' || echo 'No')"
echo "   - Markdown docs: $(find . -maxdepth 1 -name '*.md' | wc -l) files"
echo ""
echo "4. Architecture Layers:"
grep -r "class.*Service" src/core/services/*.h 2>/dev/null | grep -c "class" || echo "0"
grep -r "class.*Repository" src/core/repositories/*.h 2>/dev/null | grep -c "class" || echo "0"
grep -r "class.*Controller" src/ui/controllers/*.h 2>/dev/null | grep -c "class" || echo "0"
echo ""
echo "5. Potential Issues to Address:"
echo "   - Large methods (>100 lines): $(grep -rn "^[^/]*{$" src/ui/windows/MainWindow.cc | wc -l)"
echo "   - TODO/FIXME comments: $(grep -r "TODO\|FIXME" src/ | wc -l)"
echo "   - Compiler warnings: Check build output"
echo ""
